baseURL = 'https://napisnest.com'
languageCode = 'en-us'
title = 'TekTribe Chronicles'
theme = 'Compendium'

[params]
  author = "Overseer Æ"
  description = "Compendium of the Collective"
  disableRSS = true
  disableTwitter = true
  hero_banner = "images/tektribe-awakening-banner.jpg"
