baseURL = 'https://napisnest.com'
languageCode = 'en-us'
title = 'TekTribe Chronicles'
theme = 'Compendium'

[params]
  author = "Overseer AE"
  description = "Compendium of the Collective"
  disableRSS = true
  disableTwitter = true
