[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.164.0"

[[redirects]]
  from = "https://napisnest.com/*"
  to = "https://roaring-kitsune-13ad5f.netlify.app/:splat"
  status = 301
  force = false
