[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.164.0"

[template]
  baseURL = "https://overseer.ae"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true
